# All this file was generated by LLM

# The file take a given trained model and randomly choose a decided amount of images to see their top K images according to the chosen value of the related parameter

import glob
import os
import random
import re

import matplotlib.pyplot as plt
import numpy as np
import torch
import torchvision.transforms as T
from PIL import Image

# --- Configuration for VIGOR ---
MODEL_NAME = 'convnext_base.fb_in22k_ft_in1k_384'
WEIGHTS_PATH = "./vigor_same_congeo/convnext_base.fb_in22k_ft_in1k_384/203235/weights_e19_44.3991.pth" # Chosen model
VIGOR_ROOT = "/mnt/vigor"
IMG_SIZE = 384
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
IMAGES_SAMPLE = 3 # Number of random images selected to see its topK
K = 5 # To change the number of top images returned 
def load_and_preprocess_image(img_path, img_size, mean, std):
    img = Image.open(img_path).convert('RGB')
    transform = T.Compose([
        T.Resize((img_size, img_size)),
        T.ToTensor(),
        T.Normalize(mean=mean, std=std)
    ])
    return transform(img).unsqueeze(0).to(DEVICE), img

def extract_gps_from_filename(filename):
    match = re.search(r'(-?\d+\.\d+)[,_](-?\d+\.\d+)', filename)
    if match:
        return float(match.group(1)), float(match.group(2))
    return None, None

if __name__ == '__main__':
    from congeo.model import TimmModel_ConGeo
    
    print("Chargement du modèle...")
    model = TimmModel_ConGeo(MODEL_NAME, pretrained=False, img_size=IMG_SIZE)
    model.load_state_dict(torch.load(WEIGHTS_PATH, map_location=DEVICE))
    model = model.to(DEVICE).eval()
    
    data_config = model.get_config()
    mean, std = data_config["mean"], data_config["std"]

    # 1. Scan folder by images extention
    print("Scan folder")
    all_files = []
    for ext in ["*.jpg", "*.JPG", "*.png", "*.PNG"]:
        all_files.extend(glob.glob(os.path.join(VIGOR_ROOT, f"**/{ext}"), recursive=True))
    
    satellite_paths = []
    ground_paths = []
    
    # 2. Splitting by parent folder
    for p in all_files:
        p_lower = p.lower()
        if "satellite" in p_lower:
            satellite_paths.append(p)
        elif "panorama" in p_lower:
            ground_paths.append(p)
    

    satellite_paths = sorted(satellite_paths)
    ground_paths = sorted(ground_paths)

    # 3. Global satellite descriptor
    sat_features = []
    with torch.no_grad():
        for path in satellite_paths:
            img_tensor, _ = load_and_preprocess_image(path, IMG_SIZE, mean, std)
            feat = model(img_tensor)
            feat = torch.nn.functional.normalize(feat, p=2, dim=1)
            sat_features.append(feat)
    sat_features = torch.cat(sat_features, dim=0)

    output_dir = "./top5_retrieval_results_vigor"
    os.makedirs(output_dir, exist_ok=True)

    random_queries = random.sample(ground_paths, k=min(IMAGES_SAMPLE, len(ground_paths)))

    for idx_tirage, query_path in enumerate(random_queries):
        query_filename = os.path.basename(query_path)
        print(f"[{idx_tirage+1}/{len(random_queries)}] Request : {query_filename}")
        
        with torch.no_grad():
            query_tensor, img_query_pil = load_and_preprocess_image(query_path, IMG_SIZE, mean, std)
            query_feature = model(query_tensor)
            query_feature = torch.nn.functional.normalize(query_feature, p=2, dim=1)

        scores = torch.matmul(query_feature, sat_features.T).squeeze(0)
        topk_scores, topk_indices = torch.topk(scores, k=K) # the parameter k is the top k images corresponding to the given stree-view image
        topk_indices = topk_indices.cpu().numpy()
        topk_scores = topk_scores.cpu().numpy()

        fig, axes = plt.subplots(1, 6, figsize=(20, 4))
        axes[0].imshow(img_query_pil)
        axes[0].set_title(f"Request street : \n{query_filename[:12]}...", fontsize=10, fontweight='bold')
        axes[0].axis('off')

        q_lat, q_lon = extract_gps_from_filename(query_filename)

        for rank, r_idx in enumerate(topk_indices):
            sat_path = satellite_paths[r_idx]
            img_sat = Image.open(sat_path).convert('RGB')
            sat_filename = os.path.basename(sat_path)
            
            axes[rank + 1].imshow(img_sat)
            axes[rank + 1].axis('off')
            
            s_lat, s_lon = extract_gps_from_filename(sat_filename)
            is_correct = False
            if q_lat and s_lat:
                dist = ((q_lat - s_lat)**2 + (q_lon - s_lon)**2)**0.5
                is_correct = dist < 0.0015
            
            color = 'lime' if is_correct else 'red'
            rect = plt.Rectangle((0, 0), img_sat.size[0], img_sat.size[1], linewidth=6, edgecolor=color, facecolor='none')
            axes[rank + 1].add_patch(rect)
            axes[rank + 1].set_title(f"Top-{rank+1}\nSim: {topk_scores[rank]:.3f}", color=color, fontsize=9)

        plt.tight_layout()
        clean_file_id = query_filename.split(',')[0]
        output_name = os.path.join(output_dir, f"tirage_{idx_tirage+1}_id_{clean_file_id}.png")
        plt.savefig(output_name, bbox_inches='tight', dpi=150)
        plt.close()
    
    print(f"Result saved :  {output_dir}")